name: age2
description: age2 Flutter package.
version: 1.0.0
homepage: https://github.com/cybex-dev/age2
repository: https://github.com/cybex-dev/age2
documentation: https://github.com/cybex-dev/age2/wiki
issue_tracker: https://github.com/cybex-dev/age2/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: